---
title: C28105 | Microsoft Docs
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: f13afe72d53f8765cc7d1e1e2540b23f2d378d56
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 04/16/2018
---
# <a name="c28105"></a>C28105
Aviso C28105: Vazamento de recursos devido a uma exceção  
  
 O recurso especificado não é liberado quando uma exceção é gerada. A instrução especificada pelo caminho pode gerar uma exceção. Esse aviso é semelhante ao aviso [C28103](../code-quality/c28103.md), exceto que, nesse caso uma exceção está envolvida.  
  
## <a name="example"></a>Exemplo  
 O exemplo de código a seguir gera este aviso:  
  
```  
res = KeSaveFloatingPointState(buffer);  
  
res = AllocateResource(Resource);  
char *p2 = new char[10]; // could throw  
  
delete[] p2;  
FreeResource(Resource)  
```  
  
 O exemplo de código a seguir evita este aviso:  
  
```  
res = AllocateResource(Resource);  
char *p2;  
  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
FreeResource(Resource)  
```