---
title: "C6318 | Microsoft Docs"
ms.custom: ""
ms.date: "12/03/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6318"
helpviewer_keywords: 
  - "C6318"
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
caps.latest.revision: 13
caps.handback.revision: 13
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C6318
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

aviso C6318: \_\_try \/ \_\_except mal definido: o uso da constante EXCEPTION\_CONTINUE\_SEARCH ou outra constante que é avaliada como zero na expressão do filtro de exceção.  O código no bloco de manipulador de exceção não é executado  
  
 Esse aviso que indica se ocorrer uma exceção no bloco protegido do manipulador estruturado de exceção, a exceção não será tratada como a constante `EXCECPTION_CONTINUE_SEARCH` é usada na expressão de filtro de exceção.  
  
 Esse código é equivalente ao bloco protegido sem o bloco do manipulador de exceção porque o bloco do manipulador não é executado.  
  
## Exemplo  
 O código a seguir gera este aviso:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318  
  {  
    puts("Exception Occurred");  
  }  
}  
```  
  
 Para corrigir esse aviso, use o seguinte código:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *pch)  
{  
  __try   
  {  
    // assignment might fail  
    *pch = 0;  
  }   
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?  
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )  
  {  
    puts("Access violation");  
  }  
}   
```  
  
## Consulte também  
 [Instrução try\-except](/visual-cpp/cpp/try-except-statement)