---
title: "C6312 | Microsoft Docs"
ms.custom: ""
ms.date: "12/03/2016"
ms.prod: "visual-studio-dev14"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C6312"
helpviewer_keywords: 
  - "C6312"
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 13
caps.handback.revision: 13
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
---
# C6312
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

aviso C6312: Possível loop infinito: uso da constante EXCEPTION\_CONTINUE\_EXECUTION na expressão do filtro de exceção de uma exceção try  
  
 Esse aviso indica o uso de `EXCEPTION_CONTINUE_EXECUTION` constante \(ou de outra constante que é avaliada como \-1\) na expressão de filtro de um manipulador estruturado de exceção.  O uso do valor constante `EXCEPTION_CONTINUE_EXECUTION` pode resultar em um loop infinito.  Por exemplo, se uma exceção foi gerada pelo hardware, a instrução que causou a exceção será reiniciada.  Se o endereço que causou a exceção ainda estiver incorreto, outra exceção ocorrerá e será tratada da mesma maneira.  Isso causa um loop infinito.  
  
 Uma chamada explícita para `RaiseException` não causará diretamente um loop infinito, mas continuará a execução do código no bloco protegido.  Isso pode ser inesperada, e pode resultar em um loop infinito se `RaiseException` foi usado para evitar desreferenciar um ponteiro inválido.  
  
 Normalmente, `EXCEPTION_CONTINUE_EXECUTION` deve ser retornado somente por uma função chamada na expressão de filtro, que tem uma possibilidade corrigir o ponteiro que causou a exceção ou a memória subjacente.  
  
## Exemplo  
 O código a seguir gera este aviso:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Para corrigir esse aviso, use o seguinte código:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```