---
title: C6312 | Microsoft Docs
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C6312
helpviewer_keywords: C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: "13"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.workload: multiple
ms.openlocfilehash: c53735af9d16660bbd19055a67468e0a7813a260
ms.sourcegitcommit: 32f1a690fc445f9586d53698fc82c7debd784eeb
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 12/22/2017
---
# <a name="c6312"></a>C6312
Aviso C6312: possível loop infinito: use a constante exception_continue_execution na expressão de filtro de exceção de um bloco try-exceto  
  
 Esse aviso indica o uso da constante `EXCEPTION_CONTINUE_EXECUTION` (ou outra constante que é avaliada como -1) na expressão de filtro de um manipulador de exceção estruturada. Uso do valor de constante `EXCEPTION_CONTINUE_EXECUTION` pode levar a um loop infinito. Por exemplo, se uma exceção foi gerada pelo hardware, a instrução que causou a exceção será reiniciada. Se o endereço que causou a exceção é ruim ainda, outra exceção ocorrerá e ser tratada da mesma maneira. Isso faz com que um loop infinito.  
  
 Uma chamada explícita para `RaiseException` diretamente não serão causa um loop infinito, mas continuará a execução do código no bloco protegido. Isso pode ser inesperado e pode resultar em um loop infinito se `RaiseException` foi usado para evitar a referência a um ponteiro inválido.  
  
 Normalmente, `EXCEPTION_CONTINUE_EXECUTION` devem ser retornados somente por uma função chamada na expressão de filtro, que tem a oportunidade de corrigir o o ponteiro que causou a exceção ou a memória subjacente.  
  
## <a name="example"></a>Exemplo  
 O código a seguir gera este aviso:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Para corrigir esse aviso, use o seguinte código:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```